# Jekyll configuration file
title: Jai Makhija
#email: jaimakhija98@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaimakhija.com"
domain: jaimakhija.com

author:
  name: Jai Makhija
  email: jaimakhija98@gmail.com

nav_paths:
  - "links.markdown"
  - "bookshelf.markdown"
  - "summaries.markdown"
  - "pow.markdown"

collections:
  summaries:
    output: true
    permalink: /summaries/:name/

# Build settings
theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
minima:
  skin: dark # or auto if you want it to switch with your system settings.

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
